# core.series.Series { #ammonyte.core.series.Series }

```python
core.series.Series()
```

[[source]](https://github.com/LinkedEarth/Ammonyte/blob/main/ammonyte/core/series.py#L24-L489){.source-link target="_blank"}

Ammonyte series object, launching point for most ammonyte analysis.

Child of pyleoclim.Series, so shares all methods with pyleoclim.Series plus those
defined here.

## Methods

| Name | Description |
| --- | --- |
| [determinism](#ammonyte.core.series.Series.determinism) | Calculate determinism of a series |
| [embed](#ammonyte.core.series.Series.embed) | Create a time delay embedding from an ammonyte.Series object |
| [from_csv](#ammonyte.core.series.Series.from_csv) | Load an ammonyte Series from a CSV file with pyleoclim metadata format. |
| [kstest](#ammonyte.core.series.Series.kstest) | Detect tipping points using Kolmogorov-Smirnov test |
| [laminarity](#ammonyte.core.series.Series.laminarity) | Calculate laminarity of a series |
| [ruptures](#ammonyte.core.series.Series.ruptures) | Detect transitions using ruptures change point detection |

### determinism { #ammonyte.core.series.Series.determinism }

```python
core.series.Series.determinism(window_size, overlap, m, tau, eps)
```

Calculate determinism of a series

Note that series must be evenly spaced for this method.
See interp, bin, and gkernel methods in parent class pyleoclim.Series for details.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**window_size**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation}</code>

:   Size of window to use when calculating recurrence plots for determinism statistic. Note this is in units of the time axis.

<code>[**overlap**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation}</code>

:   Amount of overlap to allow between windows. Note this is in units of the time axis.

<code>[**m**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation}</code>

:   Embedding dimension to use when performing time delay embedding,

<code>[**tau**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation}</code>

:   Time delay to use when performing time delay embedding

<code>[**eps**]{.parameter-name} [:]{.parameter-annotation-sep} [[float](`float`)]{.parameter-annotation}</code>

:   Size of radius to use to calculate recurrence matrix

#### Returns {.doc-section .doc-section-returns}

<code>[**det_series**]{.parameter-name} [:]{.parameter-annotation-sep} [[ammonyte](`ammonyte`).[Series](`ammonyte.Series`)]{.parameter-annotation}</code>

:   Ammonyte.Series object containing time series of the determinism statistic

[[source]](https://github.com/LinkedEarth/Ammonyte/blob/main/ammonyte/core/series.py#L126-L204){.source-link target="_blank"}

### embed { #ammonyte.core.series.Series.embed }

```python
core.series.Series.embed(m, tau=None)
```

Create a time delay embedding from an ammonyte.Series object

#### Parameters {.doc-section .doc-section-parameters}

<code>[**m**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation}</code>

:   Embedding dimension (number of delay coordinates).

<code>[**tau**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   Time delay for the embedding. If None, estimated automatically via the first minimum of mutual information using ammonyte.utils.parameters.tau_search.

#### Returns {.doc-section .doc-section-returns}

<code>[**TimeEmbeddedSeries**]{.parameter-name} [:]{.parameter-annotation-sep} [[ammonyte](`ammonyte`).[TimeEmbeddedSeries](`ammonyte.TimeEmbeddedSeries`)]{.parameter-annotation}</code>

:   Time delay embedded representation of the series.

#### See Also {.doc-section .doc-section-see-also}


ammonyte.utils.parameters.tau_search

ammonyte.TimeEmbeddedSeries

[[source]](https://github.com/LinkedEarth/Ammonyte/blob/main/ammonyte/core/series.py#L72-L124){.source-link target="_blank"}

### from_csv { #ammonyte.core.series.Series.from_csv }

```python
core.series.Series.from_csv(file_path)
```

Load an ammonyte Series from a CSV file with pyleoclim metadata format.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**file_path**]{.parameter-name} [:]{.parameter-annotation-sep} [[str](`str`)]{.parameter-annotation}</code>

:   Path to the CSV file with pyleoclim metadata header format (### delimited)

#### Returns {.doc-section .doc-section-returns}

<code>[]{.parameter-name} [:]{.parameter-annotation-sep} [[ammonyte](`ammonyte`).[Series](`ammonyte.Series`)]{.parameter-annotation}</code>

:   An ammonyte Series object loaded from the CSV file

#### Examples {.doc-section .doc-section-examples}

```python
>>> ts = ammonyte.Series.from_csv('data/NGRIP.csv')
```

[[source]](https://github.com/LinkedEarth/Ammonyte/blob/main/ammonyte/core/series.py#L31-L70){.source-link target="_blank"}

### kstest { #ammonyte.core.series.Series.kstest }

```python
core.series.Series.kstest(
    w_min,
    w_max,
    n_w=15,
    d_c=0.75,
    n_c=3,
    s_c=1.5,
    x_c=None,
)
```

Detect tipping points using Kolmogorov-Smirnov test

Applies sliding window KS test to detect abrupt transitions in time series data using the method of Bagniewski et al. (2021).

#### Parameters {.doc-section .doc-section-parameters}

<code>[**w_min**]{.parameter-name} [:]{.parameter-annotation-sep} [[float](`float`)]{.parameter-annotation}</code>

:   Size of smallest sliding window in time units

<code>[**w_max**]{.parameter-name} [:]{.parameter-annotation-sep} [[float](`float`)]{.parameter-annotation}</code>

:   Size of largest sliding window in time units

<code>[**n_w**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [15]{.parameter-default}</code>

:   Number of window lengths to test. Default is 15

<code>[**d_c**]{.parameter-name} [:]{.parameter-annotation-sep} [[float](`float`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [0.75]{.parameter-default}</code>

:   Cut-off threshold for KS statistic. Default is 0.75

<code>[**n_c**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [3]{.parameter-default}</code>

:   Minimum sample size per window. Default is 3

<code>[**s_c**]{.parameter-name} [:]{.parameter-annotation-sep} [[float](`float`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [1.5]{.parameter-default}</code>

:   Standard deviation ratio threshold. Default is 1.5

<code>[**x_c**]{.parameter-name} [:]{.parameter-annotation-sep} [[float](`float`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   Change threshold. If None, auto-calculated

#### Returns {.doc-section .doc-section-returns}

<code>[]{.parameter-name} [:]{.parameter-annotation-sep} [[DeterministicTransitions](`ammonyte.core.transitions.DeterministicTransitions`)]{.parameter-annotation}</code>

:   Object containing detected transitions with their corresponding  KS D-statistics and p-values, plus methods for analysis

#### Examples {.doc-section .doc-section-examples}

Basic tipping point detection:

```{python}
import os, ammonyte as amt
ngrip = amt.Series.from_csv(os.path.join(os.path.dirname(amt.__file__), 'data', 'NGRIP.csv'))
transitions = ngrip.kstest(w_min=0.12, w_max=2.5, n_w=15, d_c=0.77, n_c=3, s_c=2, x_c=0.8)
print(transitions)
```

Access transition statistics:

```{python}
print(f"D-statistics: {transitions.d_statistics}")
print(f"P-values: {transitions.p_values}")
```

Plot the results:

```{python}
transitions.plot()
```

#### See Also {.doc-section .doc-section-see-also}

DeterministicTransitions.plot : Visualize detected transitions

#### References {.doc-section .doc-section-references}


.. [1] Bagniewski, W., Ghil, M., & Rousseau, D. D. (2021). 
       Automatic detection of abrupt transitions in paleoclimate records. 
       Chaos: An Interdisciplinary Journal of Nonlinear Science, 31(11), 113129.
       https://doi.org/10.1063/5.0062543


.. [2] Kolmogorov, A. (1933). Sulla determinazione empirica di una legge 
       di distribuzione. Giornale dell'Istituto Italiano degli Attuari, 4, 83-91.

.. [3] Smirnov, N. (1948). Table for estimating the goodness of fit of 
       empirical distributions. The Annals of Mathematical Statistics, 19(2), 279-281.

[[source]](https://github.com/LinkedEarth/Ammonyte/blob/main/ammonyte/core/series.py#L286-L384){.source-link target="_blank"}

### laminarity { #ammonyte.core.series.Series.laminarity }

```python
core.series.Series.laminarity(window_size, overlap, m, tau, eps)
```

Calculate laminarity of a series

Note that series must be evenly spaced for this method.
See interp, bin, and gkernel methods in parent class pyleoclim.Series for details.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**window_size**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation}</code>

:   Size of window to use when calculating recurrence plots for determinism statistic. Note this is in units of the time axis.

<code>[**overlap**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation}</code>

:   Amount of overlap to allow between windows Note this is in units of the time axis.

<code>[**m**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation}</code>

:   Embedding dimension to use when performing time delay embedding,

<code>[**tau**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation}</code>

:   Time delay to use when performing time delay embedding

<code>[**eps**]{.parameter-name} [:]{.parameter-annotation-sep} [[float](`float`)]{.parameter-annotation}</code>

:   Size of radius to use to calculate recurrence matrix

#### Returns {.doc-section .doc-section-returns}

<code>[**lam_series**]{.parameter-name} [:]{.parameter-annotation-sep} [[ammonyte](`ammonyte`).[Series](`ammonyte.Series`)]{.parameter-annotation}</code>

:   Ammonyte.Series object containing time series of the laminarity statistic

[[source]](https://github.com/LinkedEarth/Ammonyte/blob/main/ammonyte/core/series.py#L206-L284){.source-link target="_blank"}

### ruptures { #ammonyte.core.series.Series.ruptures }

```python
core.series.Series.ruptures(
    algo='Pelt',
    cost='rbf',
    pen=None,
    n_bkps=None,
    min_size=2,
    jump=1,
    width=None,
    params=None,
)
```

Detect transitions using ruptures change point detection

Applies ruptures algorithms for offline change point detection. 

#### Parameters {.doc-section .doc-section-parameters}

<code>[**algo**]{.parameter-name} [:]{.parameter-annotation-sep} [[str](`str`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [\'Pelt\']{.parameter-default}</code>

:   Search algorithm. Default is 'Pelt' Options: 'Pelt', 'Dynp', 'Binseg', 'BottomUp', 'Window', 'KernelCPD'

<code>[**cost**]{.parameter-name} [:]{.parameter-annotation-sep} [[str](`str`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [\'rbf\']{.parameter-default}</code>

:   Cost function (type of change to detect). Default is 'rbf' Options: 'l1', 'l2', 'rbf', 'normal', 'ar', 'linear', 'rank', 'mahalanobis', 'cosine', 'clinear'

<code>[**pen**]{.parameter-name} [:]{.parameter-annotation-sep} [[float](`float`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   Penalty parameter controlling sensitivity to changepoints (higher = fewer changepoints)  **What is penalty?** The algorithm minimizes: [fit error] + [number of changepoints × pen] - Low penalty → more changepoints (risk: overfitting, detecting noise as transitions) - High penalty → fewer changepoints (risk: missing real transitions)  **Choosing penalty is a user decision** based on your data characteristics, expected transition frequency, and tolerance for false positives vs. false negatives. There is no single "correct" penalty value - it requires experimentation and domain knowledge.  **Example approaches for selecting penalty:** 1. **Fixed empirical values**: pen = 5, 10, 20, etc. (experiment to find what works) 2. **Information criteria** (linear penalties that balance fit vs. complexity):    - AIC (Akaike Information Criterion) - more liberal, detects more changepoints    - BIC (Bayesian Information Criterion) - more conservative, sample-size dependent    - mBIC (modified BIC) - even more conservative     **Note**: The exact formula for each criterion depends on the statistical model    and cost function used. For theoretical details, see ruptures documentation.

<code>[**n_bkps**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   Exact number of breakpoints to detect (alternative to penalty-based approach) Use when you know how many transitions to expect **Note**: Cannot be used together with 'pen' - choose one or the other

<code>[**min_size**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [2]{.parameter-default}</code>

:   Minimum samples between change points. Default is 2

<code>[**jump**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [1]{.parameter-default}</code>

:   Subsample (1=all data, 5=every 5th point). Default is 1

<code>[**width**]{.parameter-name} [:]{.parameter-annotation-sep} [[int](`int`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   Window size (required for Window algorithm)

<code>[**params**]{.parameter-name} [:]{.parameter-annotation-sep} [[dict](`dict`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [None]{.parameter-default}</code>

:   Additional algorithm-specific parameters

#### Returns {.doc-section .doc-section-returns}

<code>[]{.parameter-name} [:]{.parameter-annotation-sep} [[DeterministicTransitions](`ammonyte.core.transitions.DeterministicTransitions`)]{.parameter-annotation}</code>

:   Object containing detected transitions with plot() and to_csv() methods

#### Examples {.doc-section .doc-section-examples}

Basic transition detection:

```{python}
import os, ammonyte as amt
ngrip = amt.Series.from_csv(os.path.join(os.path.dirname(amt.__file__), 'data', 'NGRIP.csv'))
transitions = ngrip.ruptures(algo='Pelt', cost='rbf', pen=5)
print(transitions)
```

Plot the results:

```{python}
transitions.plot()
```

#### References {.doc-section .doc-section-references}


.. [1] Truong, C., Oudre, L., & Vayatis, N. (2020).
       Selective review of offline change point detection methods.
       Signal Processing, 167, 107299.

[[source]](https://github.com/LinkedEarth/Ammonyte/blob/main/ammonyte/core/series.py#L386-L489){.source-link target="_blank"}